#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

# install JupyterLab extension
set -e
echo "Instalando extensiones compatibles con JupyterLab 4"
pip install jupyterlab_latex
echo "Listo."